// <auto-generated />
using System;
using FitnessCenterApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessCenterApp.Data.Migrations
{
    [DbContext(typeof(FitnessCenterDbContext))]
    partial class FitnessCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessCenterApp.Models.Client", b =>
                {
                    b.Property<int>("IdClients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Clients");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClients"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Firstname");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Gender");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Height");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone_number");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Weight");

                    b.HasKey("IdClients");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.ClientRecordsTraining", b =>
                {
                    b.Property<int>("IdClientRecordsTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Client_Records_Training");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClientRecordsTraining"));

                    b.Property<int>("IdClients")
                        .HasColumnType("int")
                        .HasColumnName("ID_Clients");

                    b.Property<int>("IdTraining")
                        .HasColumnType("int")
                        .HasColumnName("ID_Training");

                    b.Property<string>("Presence")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Presence");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Record_date");

                    b.HasKey("IdClientRecordsTraining");

                    b.HasIndex("IdClients");

                    b.HasIndex("IdTraining", "IdClients")
                        .IsUnique();

                    b.ToTable("Client_Records_Training");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.RateSubscription", b =>
                {
                    b.Property<int>("IdRateSubscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Rate_Subscription");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRateSubscription"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("NumberOfVisits")
                        .HasColumnType("int")
                        .HasColumnName("Number_of_visits");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Type");

                    b.HasKey("IdRateSubscription");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rate_Subscription");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Schedule", b =>
                {
                    b.Property<int>("IdSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Schedule");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSchedule"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("End_time");

                    b.Property<int>("IdTraining")
                        .HasColumnType("int")
                        .HasColumnName("ID_Training");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("Start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Training_date");

                    b.HasKey("IdSchedule");

                    b.HasIndex("IdTraining");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.ScheduleTrainer", b =>
                {
                    b.Property<int>("IdScheduleTrainer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Schedule_Trainer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdScheduleTrainer"));

                    b.Property<int>("IdSchedule")
                        .HasColumnType("int")
                        .HasColumnName("ID_Schedule");

                    b.Property<int>("IdTrainer")
                        .HasColumnType("int")
                        .HasColumnName("ID_Trainer");

                    b.HasKey("IdScheduleTrainer");

                    b.HasIndex("IdTrainer");

                    b.HasIndex("IdSchedule", "IdTrainer")
                        .IsUnique();

                    b.ToTable("Schedule_Trainer");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Subscription", b =>
                {
                    b.Property<int>("IdSubscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Subscription");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubscription"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("End_date");

                    b.Property<int>("IdClients")
                        .HasColumnType("int")
                        .HasColumnName("ID_Clients");

                    b.Property<int>("IdRateSubscription")
                        .HasColumnType("int")
                        .HasColumnName("ID_Rate_Subscription");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start_date");

                    b.HasKey("IdSubscription");

                    b.HasIndex("IdClients");

                    b.HasIndex("IdRateSubscription");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Trainer", b =>
                {
                    b.Property<int>("IdTrainer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Trainer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrainer"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Specialization");

                    b.HasKey("IdTrainer");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.TrainerAvailability", b =>
                {
                    b.Property<int>("IdTrainerAvailability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Trainer_Availability");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrainerAvailability"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<int>("IdTrainer")
                        .HasColumnType("int")
                        .HasColumnName("ID_Trainer");

                    b.Property<TimeSpan>("WorkEndTime")
                        .HasColumnType("time")
                        .HasColumnName("Work_end_time");

                    b.Property<TimeSpan>("WorkStartTime")
                        .HasColumnType("time")
                        .HasColumnName("Work_start_time");

                    b.HasKey("IdTrainerAvailability");

                    b.HasIndex("IdTrainer");

                    b.ToTable("Trainer_Availability");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Training", b =>
                {
                    b.Property<int>("IdTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Training");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTraining"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Intensity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Intensity");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int")
                        .HasColumnName("Max_participants");

                    b.Property<string>("Place")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Place");

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Training_name");

                    b.HasKey("IdTraining");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.ClientRecordsTraining", b =>
                {
                    b.HasOne("FitnessCenterApp.Models.Client", "Client")
                        .WithMany("ClientRecords")
                        .HasForeignKey("IdClients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Models.Training", "Training")
                        .WithMany("ClientRecords")
                        .HasForeignKey("IdTraining")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Schedule", b =>
                {
                    b.HasOne("FitnessCenterApp.Models.Training", "Training")
                        .WithMany("Schedules")
                        .HasForeignKey("IdTraining")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.ScheduleTrainer", b =>
                {
                    b.HasOne("FitnessCenterApp.Models.Schedule", "Schedule")
                        .WithMany("ScheduleTrainers")
                        .HasForeignKey("IdSchedule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Models.Trainer", "Trainer")
                        .WithMany("ScheduleTrainers")
                        .HasForeignKey("IdTrainer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Subscription", b =>
                {
                    b.HasOne("FitnessCenterApp.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdClients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCenterApp.Models.RateSubscription", "RateSubscription")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdRateSubscription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("RateSubscription");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.TrainerAvailability", b =>
                {
                    b.HasOne("FitnessCenterApp.Models.Trainer", "Trainer")
                        .WithMany("Availabilities")
                        .HasForeignKey("IdTrainer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Client", b =>
                {
                    b.Navigation("ClientRecords");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.RateSubscription", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Schedule", b =>
                {
                    b.Navigation("ScheduleTrainers");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Trainer", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ScheduleTrainers");
                });

            modelBuilder.Entity("FitnessCenterApp.Models.Training", b =>
                {
                    b.Navigation("ClientRecords");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
